FROM mambaorg/micromamba:latest

COPY --chown=$MAMBA_USER:$MAMBA_USER samtools_env.yml /samtools_env.yml

RUN micromamba install -y -n base -f /samtools_env.yml && micromamba clean --all --yes

# just exec things causing problems, not a great fix, change in Dockerfile detected?
ENV PATH "$MAMBA_ROOT_PREFIX/bin:$PATH"