name: Build and publish Docker image to github registry

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./biopython/Dockerfile
            image: ghcr.io/joeyorofino/biopython:1.7.8
          - dockerfile: ./samtools/Dockerfile
            image: ghcr.io/joeyorofino/samtools:1.20

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ matrix.image }}
 
      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
