name: Build and publish Docker image to github registry

on:
  push:
    paths-ignore:
      - '.github/workflows/build.yml'
    branches: ['change-action-matrix']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45.0.2
        with:
          dir_names: true
          json: true
      
      - name: save changed changed_directories
        id: set-output
        run: echo "changed_directories={\"dir\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  make-matrix:
    runs-on: ubuntu-latest
    needs: find-out-changes
    if: ${{ needs.find-out-changes.outputs.changed_directories != ''}}
    strategy:
      matrix: ${{ fromJson(needs.find-out-changes.outputs.changed_directories) }}
      fail-fast: true

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: manually make changes matrix
        id: changes-matrix
        run: echo "test={\"dockerfile\":\"${{ matrix.dir }}/Dockerfile\", \"context\":\"${{ matrix.dir }}\", \"image\":\"${{ env.REGISTRY }}/joeyorofino/${{ matrix.dir }}:latest\"}" >> "$GITHUB_OUTPUT"
      
      # - name: Login to registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: test
        run: echo ${{ steps.changes-matrix.outputs.test.context }}

      # - name: Build and push
      #   id: push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./${{ fromJSON(steps.changes-matrix.outputs.matrix).context }} 
      #     file: ${{steps.changes-matrix.outputs.matrix.dockferile}} 
      #     push: true
      #     tags: ${{steps.changes-matrix.outputs.matrix.image}} 
          
    
    # outputs:
    #   repo_json: ${{ steps.json-dir.outputs.repo_json }}
    #   changes_matrix: ${{ steps.changes-matrix.outputs.matrix }}


  # build-push:
  #   runs-on: ubuntu-latest
  #   needs: [make-matrix]
  #   strategy:
  #     fail-fast: true
  #     matrix: ${{ fromJson(needs.make-matrix.outputs.changes_matrix) }}

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Login to registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
 
  #     - name: Build and push
  #       id: push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./${{ matrix.context }}
  #         file: ${{ matrix.dockerfile }}
  #         push: true
  #         tags: ${{ matrix.image }}


